word_list = [
    'Precious',
    'Mellifluous',
    'Obvious',
    'Quixotic',
    'Perspicacious',
    'Ephemeral',
    'Nebulous',
    'Ineffable',
    'Mellifluous',
    'Disparate',
    'Cacophony',
    'Lethargic',
    'Epiphany',
    'Vicarious'
    'Ephemeral',
    'Serendipity',
    'Quizzical',
    'Pernicious',
    'Ineffable',
    'Incandescent'
]